"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json, re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4pdyllo$m(p4p6=s0nxp2ck+qjx=*p5x21ok*nptuy3=2nzufd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Allow the frontend dev server (Vite) to access the API during development
# CORS allowed origins (support env override, plus common local dev defaults)
_CORS_FROM_ENV = os.environ.get("CORS_ALLOWED_ORIGINS", "")
_CORS_LIST = [s.strip() for s in _CORS_FROM_ENV.split(",") if s.strip()]
_CORS_DEFAULTS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
]
CORS_ALLOWED_ORIGINS = _CORS_LIST or _CORS_DEFAULTS

# Optional: Allow all origins (useful for initial debugging; disable for production hardening)
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False") == "True"

# Optional: Regex-based CORS origins (helps cover dynamic preview domains)
# Example env value: ^https://quickserve-services.*\.vercel\.app$
_CORS_REGEX_ENV = os.environ.get("CORS_ALLOWED_ORIGIN_REGEXES", "")
if _CORS_REGEX_ENV:
    CORS_ALLOWED_ORIGIN_REGEXES = [s.strip() for s in _CORS_REGEX_ENV.split(",") if s.strip()]

# When running locally you may want to allow credentials (cookies/auth)
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "core",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
]

# Optional Cloudinary apps (only if library installed)
try:
    import cloudinary  # type: ignore
    import cloudinary_storage  # type: ignore
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    CLOUDINARY_ENABLED = True
except ImportError:
    CLOUDINARY_ENABLED = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS middleware should be placed as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploaded images)
if CLOUDINARY_ENABLED:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework + Simple JWT configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.FirebaseAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    # Ensure SimpleJWT does NOT attempt to parse Firebase Bearer tokens
    # Use Authorization: JWT <token> if you ever need SimpleJWT locally
    'AUTH_HEADER_TYPES': ('JWT',),
}


CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")

DEBUG = os.environ.get("DEBUG", "False") == "True"

try:
    import dj_database_url  # optional, only needed if DATABASE_URL provided
except ImportError:
    dj_database_url = None

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL and dj_database_url:
    DATABASES["default"] = dj_database_url.parse(DATABASE_URL)

def _load_service_account():
    """Load Firebase service account credentials.

    Priority order:
    1) FIREBASE_SERVICE_ACCOUNT_JSON (full JSON string)
    2) GOOGLE_APPLICATION_CREDENTIALS (path to JSON file)
    3) Individual FIREBASE_* env vars (legacy)
    """
    # 1) Full JSON in env var
    raw = os.environ.get("FIREBASE_SERVICE_ACCOUNT_JSON")
    if raw:
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            # Attempt to strip stray wrapping quotes
            raw2 = raw.strip().strip("'").strip('"')
            data = json.loads(raw2)
        # Normalize private_key newlines
        pk = data.get("private_key", "")
        pk = pk.replace("\\r", "")  # Remove accidental literal '\r'
        pk = pk.replace("\\n", "\n")  # Convert escaped '\n' to real newlines
        pk = pk.strip()
        data["private_key"] = pk
        return data

    # 2) Path to JSON file via GOOGLE_APPLICATION_CREDENTIALS
    gac_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if gac_path and os.path.exists(gac_path):
        try:
            with open(gac_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            pk = (data.get("private_key") or "")
            pk = pk.replace("\\r", "")
            pk = pk.replace("\\n", "\n").strip()
            data["private_key"] = pk
            return data
        except Exception:
            pass

    # 3) Fallback to individual vars (older method)
    return {
        "type": os.environ.get("FIREBASE_TYPE"),
        "project_id": os.environ.get("FIREBASE_PROJECT_ID"),
        "private_key_id": os.environ.get("FIREBASE_PRIVATE_KEY_ID"),
        "private_key": (os.environ.get("FIREBASE_PRIVATE_KEY") or "").replace("\\n", "\n").strip(),
        "client_email": os.environ.get("FIREBASE_CLIENT_EMAIL"),
        "client_id": os.environ.get("FIREBASE_CLIENT_ID"),
        "auth_uri": os.environ.get("FIREBASE_AUTH_URI"),
        "token_uri": os.environ.get("FIREBASE_TOKEN_URI"),
        "auth_provider_x509_cert_url": os.environ.get("FIREBASE_AUTH_PROVIDER_CERT_URL"),
        "client_x509_cert_url": os.environ.get("FIREBASE_CLIENT_CERT_URL"),
    }

FIREBASE_CONFIG = _load_service_account()

# If private key is missing or malformed, disable firebase config gracefully so server boots.
_pk = (FIREBASE_CONFIG or {}).get("private_key", "")
if not _pk.startswith("-----BEGIN PRIVATE KEY-----"):
    FIREBASE_CONFIG = {}

# Optional: bootstrap admin privileges by UID (comma-separated list of Firebase UIDs)
# Useful for local development or first-admin promotion when Firestore roles aren't yet set.
ADMIN_BOOTSTRAP_UIDS = os.environ.get("ADMIN_BOOTSTRAP_UIDS", "")